logging:
  level:
    root: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
  profiles:
    include: oauth
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

server:
  port: 8089